name: Wildlife System CI-CD

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

  jobs:
    test-and-report:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout code
          uses: actions/checkout@v1

        - name: Setup Node.js
          uses: actions/setup-node@v1
          with:
            node-version: '22.20.0'

        - name: Install dependencies
          run: |
            cd backend
            npm install

        - name: Run Mocha tests
          run: |
            cd backend
            npm test

        - name: Upload test reports
          if: always() # Ensure this step runs even if tests fail
          uses: actions/upload-artifact@v1
          with:
            name: mocha-html-reports
            path: backend/test-reports/mocha-html